Repository Deepomatic/deepomatic-client-python, pull requests merged in 2019-10, with the labels that each got.

#65 APP_ID is now optional
  README.md
  deepomatic/api/client.py
  deepomatic/api/http_helper.py
  demo.py
  tests/test_client.py
Labels: READY, enhancement

#66 Cleanup: more HTTPRetry default parameters in HTTPRetry.Default
  deepomatic/api/http_retry.py
Labels: READY, tech debt

#68 Fix code smell
  demo.py
  tests/test_client.py
Labels: READY, tech debt

#67 Improve integration
  .dockerignore
  .gitignore
  .travis.yml
  Makefile
  deploy/Dockerfile
  deploy/install.sh
  dmake.yml
  requirements.dev.txt
Labels: READY, tech debt

#72 Task and Task exceptions str(): oneline
  deepomatic/api/exceptions.py
  deepomatic/api/resource.py
  tests/test_client.py
Labels: READY
